# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a711b850ecd55c8d1714710e270eb30711561fe33af2ef6775924e2e62858bf18f338b27a39e0a67968d68f924c945142493b02687e50253bd422fcf1baa171

test:
  secret_key_base: 07eb19f3e8ad9c0288cd708c3b528a5139781d83f022720ea7e8bc633802f023dc0c8a9321cf4c919a0d45a9745ad0c506b2d29f952a36c49b692a4399730b5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
